import crypto from 'crypto';
import { createPatch } from 'diff';

export interface FileDiff {
  readonly filePath: string;
  readonly additions: number;
  readonly deletions: number;
  readonly changedLines: number;
  readonly originalHash: string;
  readonly proposedHash: string;
  readonly unifiedDiff: string;
}

export class DiffEngine {
  private readonly maxDisplayDiffLines: number;

  constructor(maxDisplayDiffLines: number = 100) {
    this.maxDisplayDiffLines = maxDisplayDiffLines;
  }

  /**
   * Computes SHA-256 hash of a string
   */
  computeHash(content: string | null): string {
    if (content === null || content === undefined) {
      return '';
    }
    return crypto.createHash('sha256').update(content, 'utf-8').digest('hex');
  }

  /**
   * Compares original content against proposed content to generate structured diff metrics
   */
  generateDiff(filePath: string, originalContent: string | null, proposedContent: string): FileDiff {
    const oldStr = originalContent ?? '';
    const newStr = proposedContent ?? '';

    const originalHash = this.computeHash(originalContent);
    const proposedHash = this.computeHash(newStr);

    // If both contents are identical
    if (oldStr === newStr) {
      return {
        filePath,
        additions: 0,
        deletions: 0,
        changedLines: 0,
        originalHash,
        proposedHash,
        unifiedDiff: ''
      };
    }

    const headerOld = originalContent === null ? '/dev/null' : `a/${filePath}`;
    const headerNew = `b/${filePath}`;
    const patch = createPatch(filePath, oldStr, newStr, headerOld, headerNew);

    const lines = patch.split('\n');
    let additions = 0;
    let deletions = 0;

    // Skip the first 4 header lines generated by createPatch
    for (let i = 4; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith('+') && !line.startsWith('+++')) {
        additions++;
      } else if (line.startsWith('-') && !line.startsWith('---')) {
        deletions++;
      }
    }

    // Format display lines safely
    let displayLines = lines.slice(2); // Omit timestamps
    if (displayLines.length > this.maxDisplayDiffLines) {
      const remaining = displayLines.length - this.maxDisplayDiffLines;
      displayLines = [
        ...displayLines.slice(0, this.maxDisplayDiffLines),
        `... [${remaining} more lines truncated for display] ...`
      ];
    }

    return {
      filePath,
      additions,
      deletions,
      changedLines: additions + deletions,
      originalHash,
      proposedHash,
      unifiedDiff: displayLines.join('\n')
    };
  }
}
