import path from 'path';
import { ActionProposal, OperationType } from '../core/types.js';

export interface ProposalCandidate {
  readonly providerId: string;
  readonly proposal: ActionProposal;
  readonly riskScore?: number;
}

export interface DisagreementAnalysis {
  readonly disagreementScore: number; // 0.0 (full agreement) to 1.0 (extreme disagreement)
  readonly consensus: boolean;
  readonly riskEscalation: boolean;
  readonly reasons: readonly string[];
  readonly dominantProposal?: ActionProposal;
}

export class ModelDisagreementDetector {
  /**
   * Compares action proposals generated by multiple independent model providers for the same goal.
   * Deterministically calculates a disagreement score and determines risk escalation requirements.
   */
  analyze(candidates: readonly ProposalCandidate[]): DisagreementAnalysis {
    if (candidates.length <= 1) {
      return {
        disagreementScore: 0.0,
        consensus: true,
        riskEscalation: false,
        reasons: [],
        dominantProposal: candidates[0]?.proposal
      };
    }

    const reasons: string[] = [];
    let disagreementScore = 0.0;
    let riskEscalation = false;

    const first = candidates[0].proposal;

    for (let i = 1; i < candidates.length; i++) {
      const current = candidates[i].proposal;

      // 1. Check Operation Type Disagreement
      if (first.operation !== current.operation) {
        disagreementScore += 0.4;
        reasons.push(
          `Operation mismatch between providers "${candidates[0].providerId}" (${first.operation}) and "${candidates[i].providerId}" (${current.operation}).`
        );
      }

      // 2. Check Target Path Disagreement
      const pathA = first.targetPath ? path.normalize(first.targetPath).toLowerCase() : '';
      const pathB = current.targetPath ? path.normalize(current.targetPath).toLowerCase() : '';
      if (pathA !== pathB) {
        disagreementScore += 0.35;
        reasons.push(
          `Target path mismatch between providers: "${first.targetPath || 'none'}" vs "${current.targetPath || 'none'}".`
        );
      }

      // 3. Check Critical Asset Involvement
      const targetsCritical = [pathA, pathB].some(p => p.includes('.env') || p.includes('.git'));
      if (targetsCritical) {
        disagreementScore += 0.25;
        riskEscalation = true;
        reasons.push('Model proposals involve critical security assets (.env / .git). Escescalating risk.');
      }

      // 4. Check Risk Score Disparity
      const scoreA = candidates[0].riskScore ?? 0;
      const scoreB = candidates[i].riskScore ?? 0;
      if (Math.abs(scoreA - scoreB) >= 30) {
        disagreementScore += 0.2;
        reasons.push(`Significant risk score disparity between model providers (${scoreA} vs ${scoreB}).`);
      }
    }

    // Clamp score to max 1.0
    disagreementScore = Math.min(1.0, Math.round(disagreementScore * 100) / 100);

    const consensus = disagreementScore < 0.25;
    if (disagreementScore >= 0.3) {
      riskEscalation = true;
    }

    return {
      disagreementScore,
      consensus,
      riskEscalation,
      reasons,
      dominantProposal: first
    };
  }
}
